// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Models;

namespace WebApi.Migrations.Warehouse
{
    [DbContext(typeof(WarehouseContext))]
    [Migration("20191114113407_seed3")]
    partial class seed3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApi.Models.ColumnModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<Guid>("RoomId");

                    b.HasKey("Id");

                    b.ToTable("Columns");

                    b.HasData(
                        new
                        {
                            Id = new Guid("13206fd2-49e0-4221-8351-d84aea7f4aef"),
                            Name = "glowna",
                            RoomId = new Guid("1a00f373-fa09-448c-944c-ada6ab18af19")
                        },
                        new
                        {
                            Id = new Guid("b4b59f14-f80b-4ceb-8373-d5c6a1aaaa0a"),
                            Name = "boczna",
                            RoomId = new Guid("1a00f373-fa09-448c-944c-ada6ab18af19")
                        });
                });

            modelBuilder.Entity("WebApi.Models.ItemModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("ColumnId");

                    b.Property<string>("ItemName");

                    b.Property<Guid>("PlaceId");

                    b.Property<int>("Quantity");

                    b.Property<Guid>("RackId");

                    b.Property<Guid>("RoomId");

                    b.Property<Guid>("ShelfId");

                    b.Property<Guid>("SideId");

                    b.Property<Guid>("WarehouseId");

                    b.HasKey("Id");

                    b.HasIndex("ColumnId");

                    b.HasIndex("PlaceId");

                    b.HasIndex("RackId");

                    b.HasIndex("RoomId");

                    b.HasIndex("ShelfId");

                    b.HasIndex("SideId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Item");

                    b.HasData(
                        new
                        {
                            Id = new Guid("323751b8-f1ae-4cb1-9a87-48297a73bc4a"),
                            ColumnId = new Guid("13206fd2-49e0-4221-8351-d84aea7f4aef"),
                            ItemName = "Przedmiot",
                            PlaceId = new Guid("3322ed60-de81-4b85-b4d6-26634c5bfcb8"),
                            Quantity = 20,
                            RackId = new Guid("f6a93814-cb11-4a99-8659-47a64b209d87"),
                            RoomId = new Guid("1a00f373-fa09-448c-944c-ada6ab18af19"),
                            ShelfId = new Guid("837e266f-a553-4ba2-8709-a8fd33d34ce1"),
                            SideId = new Guid("3747aa08-5b1c-489d-9de0-d651ef339384"),
                            WarehouseId = new Guid("4ee12178-18d2-4014-b07a-4e202c2dfa81")
                        },
                        new
                        {
                            Id = new Guid("14610eaf-c519-4751-abe9-3bd576548c89"),
                            ColumnId = new Guid("b4b59f14-f80b-4ceb-8373-d5c6a1aaaa0a"),
                            ItemName = "Przedmiot",
                            PlaceId = new Guid("3104557b-e8cd-4bcf-bae5-2013d447b9cc"),
                            Quantity = 20,
                            RackId = new Guid("ca243217-66de-497e-9af7-2085627a9e40"),
                            RoomId = new Guid("1a00f373-fa09-448c-944c-ada6ab18af19"),
                            ShelfId = new Guid("2d732ade-105e-4f58-a047-3eb86619044a"),
                            SideId = new Guid("ab2231ef-660d-4288-801c-bf5afddc6646"),
                            WarehouseId = new Guid("4ee12178-18d2-4014-b07a-4e202c2dfa81")
                        },
                        new
                        {
                            Id = new Guid("ed8fec3a-f6ac-47ae-93f6-59cf3dd4f7dd"),
                            ColumnId = new Guid("b4b59f14-f80b-4ceb-8373-d5c6a1aaaa0a"),
                            ItemName = "Przedmiot",
                            PlaceId = new Guid("3bf832d4-90b4-469a-8932-b879cfb1485b"),
                            Quantity = 20,
                            RackId = new Guid("16f7c8e2-990e-4f64-9805-7cde202f32bf"),
                            RoomId = new Guid("1a00f373-fa09-448c-944c-ada6ab18af19"),
                            ShelfId = new Guid("2c39d693-7b6f-47ee-bde7-4f10ea8b5726"),
                            SideId = new Guid("b8d92626-9ec5-4979-8b00-3d868014bf9a"),
                            WarehouseId = new Guid("4ee12178-18d2-4014-b07a-4e202c2dfa81")
                        },
                        new
                        {
                            Id = new Guid("63239988-86d3-494a-a3dc-6b6199dbd3cd"),
                            ColumnId = new Guid("b4b59f14-f80b-4ceb-8373-d5c6a1aaaa0a"),
                            ItemName = "Przedmiot",
                            PlaceId = new Guid("c68cb847-f9e0-4b2a-b570-f36f0938ce9a"),
                            Quantity = 20,
                            RackId = new Guid("16f7c8e2-990e-4f64-9805-7cde202f32bf"),
                            RoomId = new Guid("1a00f373-fa09-448c-944c-ada6ab18af19"),
                            ShelfId = new Guid("09b9ea1c-bb99-48ad-b8f1-caa323f0d4d4"),
                            SideId = new Guid("d7681aa0-372b-4d2e-a664-77d6734ae497"),
                            WarehouseId = new Guid("4ee12178-18d2-4014-b07a-4e202c2dfa81")
                        },
                        new
                        {
                            Id = new Guid("f0d09218-fc99-4b14-b7e7-63a50283130c"),
                            ColumnId = new Guid("b4b59f14-f80b-4ceb-8373-d5c6a1aaaa0a"),
                            ItemName = "Przedmiot",
                            PlaceId = new Guid("23ef368b-c23c-4010-874d-5a80a5b74621"),
                            Quantity = 20,
                            RackId = new Guid("16f7c8e2-990e-4f64-9805-7cde202f32bf"),
                            RoomId = new Guid("1a00f373-fa09-448c-944c-ada6ab18af19"),
                            ShelfId = new Guid("279cb11b-3056-4e30-b185-47964b851b69"),
                            SideId = new Guid("d7681aa0-372b-4d2e-a664-77d6734ae497"),
                            WarehouseId = new Guid("4ee12178-18d2-4014-b07a-4e202c2dfa81")
                        },
                        new
                        {
                            Id = new Guid("6ae171ed-6f86-4070-8f4a-3b8ca4215549"),
                            ColumnId = new Guid("b4b59f14-f80b-4ceb-8373-d5c6a1aaaa0a"),
                            ItemName = "Przedmiot",
                            PlaceId = new Guid("a1db5294-7e66-4dc5-b2e7-8905500250b8"),
                            Quantity = 20,
                            RackId = new Guid("16f7c8e2-990e-4f64-9805-7cde202f32bf"),
                            RoomId = new Guid("1a00f373-fa09-448c-944c-ada6ab18af19"),
                            ShelfId = new Guid("279cb11b-3056-4e30-b185-47964b851b69"),
                            SideId = new Guid("d7681aa0-372b-4d2e-a664-77d6734ae497"),
                            WarehouseId = new Guid("4ee12178-18d2-4014-b07a-4e202c2dfa81")
                        });
                });

            modelBuilder.Entity("WebApi.Models.PlaceModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<Guid>("ShelfId");

                    b.HasKey("Id");

                    b.ToTable("Place");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3322ed60-de81-4b85-b4d6-26634c5bfcb8"),
                            Name = "srodek",
                            ShelfId = new Guid("837e266f-a553-4ba2-8709-a8fd33d34ce1")
                        },
                        new
                        {
                            Id = new Guid("3104557b-e8cd-4bcf-bae5-2013d447b9cc"),
                            Name = "srodek",
                            ShelfId = new Guid("2d732ade-105e-4f58-a047-3eb86619044a")
                        },
                        new
                        {
                            Id = new Guid("3bf832d4-90b4-469a-8932-b879cfb1485b"),
                            Name = "srodek",
                            ShelfId = new Guid("2c39d693-7b6f-47ee-bde7-4f10ea8b5726")
                        },
                        new
                        {
                            Id = new Guid("c68cb847-f9e0-4b2a-b570-f36f0938ce9a"),
                            Name = "srodek",
                            ShelfId = new Guid("09b9ea1c-bb99-48ad-b8f1-caa323f0d4d4")
                        },
                        new
                        {
                            Id = new Guid("23ef368b-c23c-4010-874d-5a80a5b74621"),
                            Name = "poczatek",
                            ShelfId = new Guid("279cb11b-3056-4e30-b185-47964b851b69")
                        },
                        new
                        {
                            Id = new Guid("a1db5294-7e66-4dc5-b2e7-8905500250b8"),
                            Name = "koniec",
                            ShelfId = new Guid("279cb11b-3056-4e30-b185-47964b851b69")
                        });
                });

            modelBuilder.Entity("WebApi.Models.RackModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("ColumnsId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Rack");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f6a93814-cb11-4a99-8659-47a64b209d87"),
                            ColumnsId = new Guid("13206fd2-49e0-4221-8351-d84aea7f4aef"),
                            Name = "1"
                        },
                        new
                        {
                            Id = new Guid("ca243217-66de-497e-9af7-2085627a9e40"),
                            ColumnsId = new Guid("b4b59f14-f80b-4ceb-8373-d5c6a1aaaa0a"),
                            Name = "1"
                        },
                        new
                        {
                            Id = new Guid("16f7c8e2-990e-4f64-9805-7cde202f32bf"),
                            ColumnsId = new Guid("b4b59f14-f80b-4ceb-8373-d5c6a1aaaa0a"),
                            Name = "2"
                        });
                });

            modelBuilder.Entity("WebApi.Models.RoomModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<Guid>("WarehouseId");

                    b.HasKey("Id");

                    b.ToTable("Room");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1a00f373-fa09-448c-944c-ada6ab18af19"),
                            Name = "duzy",
                            WarehouseId = new Guid("4ee12178-18d2-4014-b07a-4e202c2dfa81")
                        });
                });

            modelBuilder.Entity("WebApi.Models.ShelfModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<Guid>("SideId");

                    b.HasKey("Id");

                    b.ToTable("Shelf");

                    b.HasData(
                        new
                        {
                            Id = new Guid("837e266f-a553-4ba2-8709-a8fd33d34ce1"),
                            Name = "2",
                            SideId = new Guid("3747aa08-5b1c-489d-9de0-d651ef339384")
                        },
                        new
                        {
                            Id = new Guid("2d732ade-105e-4f58-a047-3eb86619044a"),
                            Name = "2",
                            SideId = new Guid("ab2231ef-660d-4288-801c-bf5afddc6646")
                        },
                        new
                        {
                            Id = new Guid("2c39d693-7b6f-47ee-bde7-4f10ea8b5726"),
                            Name = "2",
                            SideId = new Guid("b8d92626-9ec5-4979-8b00-3d868014bf9a")
                        },
                        new
                        {
                            Id = new Guid("09b9ea1c-bb99-48ad-b8f1-caa323f0d4d4"),
                            Name = "2",
                            SideId = new Guid("d7681aa0-372b-4d2e-a664-77d6734ae497")
                        },
                        new
                        {
                            Id = new Guid("279cb11b-3056-4e30-b185-47964b851b69"),
                            Name = "3",
                            SideId = new Guid("d7681aa0-372b-4d2e-a664-77d6734ae497")
                        });
                });

            modelBuilder.Entity("WebApi.Models.SideModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<Guid>("RackId");

                    b.HasKey("Id");

                    b.ToTable("Side");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3747aa08-5b1c-489d-9de0-d651ef339384"),
                            Name = "1",
                            RackId = new Guid("f6a93814-cb11-4a99-8659-47a64b209d87")
                        },
                        new
                        {
                            Id = new Guid("ab2231ef-660d-4288-801c-bf5afddc6646"),
                            Name = "1",
                            RackId = new Guid("ca243217-66de-497e-9af7-2085627a9e40")
                        },
                        new
                        {
                            Id = new Guid("b8d92626-9ec5-4979-8b00-3d868014bf9a"),
                            Name = "1",
                            RackId = new Guid("16f7c8e2-990e-4f64-9805-7cde202f32bf")
                        },
                        new
                        {
                            Id = new Guid("d7681aa0-372b-4d2e-a664-77d6734ae497"),
                            Name = "2",
                            RackId = new Guid("16f7c8e2-990e-4f64-9805-7cde202f32bf")
                        });
                });

            modelBuilder.Entity("WebApi.Models.WarehouseModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Warehouse");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4ee12178-18d2-4014-b07a-4e202c2dfa81"),
                            Name = "Martyna"
                        });
                });

            modelBuilder.Entity("WebApi.Models.ItemModel", b =>
                {
                    b.HasOne("WebApi.Models.ColumnModel", "Column")
                        .WithMany()
                        .HasForeignKey("ColumnId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebApi.Models.PlaceModel", "Place")
                        .WithMany()
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebApi.Models.RackModel", "Rack")
                        .WithMany()
                        .HasForeignKey("RackId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebApi.Models.RoomModel", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebApi.Models.ShelfModel", "Shelf")
                        .WithMany()
                        .HasForeignKey("ShelfId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebApi.Models.SideModel", "Side")
                        .WithMany()
                        .HasForeignKey("SideId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebApi.Models.WarehouseModel", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
