// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Models;

namespace WebApi.Migrations.Warehouse
{
    [DbContext(typeof(WarehouseContext))]
    [Migration("20191026130316_seed")]
    partial class seed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApi.Models.ColumnModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<Guid?>("RoomId");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Columns");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b874ccf0-44b2-4219-a7c0-7921505e6d31"),
                            Name = "glowna",
                            RoomId = new Guid("acead73b-468b-48c0-b11c-f7597da9f72a")
                        });
                });

            modelBuilder.Entity("WebApi.Models.ItemModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("ColumnId");

                    b.Property<string>("ItemName");

                    b.Property<Guid?>("PlaceId");

                    b.Property<int>("Quantity");

                    b.Property<Guid?>("RackId");

                    b.Property<Guid?>("RoomId");

                    b.Property<Guid?>("ShelfId");

                    b.Property<Guid?>("WarehouseId");

                    b.HasKey("Id");

                    b.HasIndex("ColumnId");

                    b.HasIndex("PlaceId");

                    b.HasIndex("RackId");

                    b.HasIndex("RoomId");

                    b.HasIndex("ShelfId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Item");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2dbc8f7f-6c23-4e5c-aa43-1a3f8ca5efb7"),
                            ItemName = "Przedmiot",
                            PlaceId = new Guid("67d37856-b7d6-4c89-8443-67ce2f611e30"),
                            Quantity = 20,
                            RackId = new Guid("0d1e4dad-5992-46c0-b315-5745e2134bb9"),
                            RoomId = new Guid("acead73b-468b-48c0-b11c-f7597da9f72a"),
                            ShelfId = new Guid("5a26f4d0-e23f-4229-9499-ef92143831e3"),
                            WarehouseId = new Guid("07312518-892a-4e07-8cd9-f3cf25f7d1c3")
                        });
                });

            modelBuilder.Entity("WebApi.Models.PlaceModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<Guid?>("ShelfId");

                    b.HasKey("Id");

                    b.HasIndex("ShelfId");

                    b.ToTable("Place");

                    b.HasData(
                        new
                        {
                            Id = new Guid("67d37856-b7d6-4c89-8443-67ce2f611e30"),
                            Name = "srodek",
                            ShelfId = new Guid("5a26f4d0-e23f-4229-9499-ef92143831e3")
                        });
                });

            modelBuilder.Entity("WebApi.Models.RackModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("ColumnsId");

                    b.Property<string>("Name");

                    b.Property<bool>("Side");

                    b.HasKey("Id");

                    b.HasIndex("ColumnsId");

                    b.ToTable("Rack");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0d1e4dad-5992-46c0-b315-5745e2134bb9"),
                            ColumnsId = new Guid("b874ccf0-44b2-4219-a7c0-7921505e6d31"),
                            Name = "1",
                            Side = false
                        });
                });

            modelBuilder.Entity("WebApi.Models.RoomModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<Guid?>("WarehouseId");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Room");

                    b.HasData(
                        new
                        {
                            Id = new Guid("acead73b-468b-48c0-b11c-f7597da9f72a"),
                            Name = "duzy",
                            WarehouseId = new Guid("07312518-892a-4e07-8cd9-f3cf25f7d1c3")
                        });
                });

            modelBuilder.Entity("WebApi.Models.ShelfModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<Guid?>("RackId");

                    b.HasKey("Id");

                    b.HasIndex("RackId");

                    b.ToTable("Shelf");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5a26f4d0-e23f-4229-9499-ef92143831e3"),
                            Name = "2",
                            RackId = new Guid("0d1e4dad-5992-46c0-b315-5745e2134bb9")
                        });
                });

            modelBuilder.Entity("WebApi.Models.WarehouseModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Warehouse");

                    b.HasData(
                        new
                        {
                            Id = new Guid("07312518-892a-4e07-8cd9-f3cf25f7d1c3"),
                            Name = "Martyna"
                        });
                });

            modelBuilder.Entity("WebApi.Models.ColumnModel", b =>
                {
                    b.HasOne("WebApi.Models.RoomModel", "Room")
                        .WithMany("Columns")
                        .HasForeignKey("RoomId");
                });

            modelBuilder.Entity("WebApi.Models.ItemModel", b =>
                {
                    b.HasOne("WebApi.Models.ColumnModel", "Column")
                        .WithMany("Item")
                        .HasForeignKey("ColumnId");

                    b.HasOne("WebApi.Models.PlaceModel", "Place")
                        .WithMany()
                        .HasForeignKey("PlaceId");

                    b.HasOne("WebApi.Models.RackModel", "Rack")
                        .WithMany()
                        .HasForeignKey("RackId");

                    b.HasOne("WebApi.Models.RoomModel", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId");

                    b.HasOne("WebApi.Models.ShelfModel", "Shelf")
                        .WithMany()
                        .HasForeignKey("ShelfId");

                    b.HasOne("WebApi.Models.WarehouseModel", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId");
                });

            modelBuilder.Entity("WebApi.Models.PlaceModel", b =>
                {
                    b.HasOne("WebApi.Models.ShelfModel", "Shelf")
                        .WithMany("Place")
                        .HasForeignKey("ShelfId");
                });

            modelBuilder.Entity("WebApi.Models.RackModel", b =>
                {
                    b.HasOne("WebApi.Models.ColumnModel", "Columns")
                        .WithMany("Rack")
                        .HasForeignKey("ColumnsId");
                });

            modelBuilder.Entity("WebApi.Models.RoomModel", b =>
                {
                    b.HasOne("WebApi.Models.WarehouseModel", "Warehouse")
                        .WithMany("Room")
                        .HasForeignKey("WarehouseId");
                });

            modelBuilder.Entity("WebApi.Models.ShelfModel", b =>
                {
                    b.HasOne("WebApi.Models.RackModel", "Rack")
                        .WithMany("Shelf")
                        .HasForeignKey("RackId");
                });
#pragma warning restore 612, 618
        }
    }
}
