// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Models;

namespace WebApi.Migrations.Warehouse
{
    [DbContext(typeof(WarehouseContext))]
    [Migration("20191026210716_seed2")]
    partial class seed2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApi.Models.ColumnModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<Guid>("RoomId");

                    b.HasKey("Id");

                    b.ToTable("Columns");

                    b.HasData(
                        new
                        {
                            Id = new Guid("98ea72f0-c968-49be-8b07-a6c853bf0f9f"),
                            Name = "glowna",
                            RoomId = new Guid("dd20f32a-8709-4880-99bb-c58b4c701c77")
                        });
                });

            modelBuilder.Entity("WebApi.Models.ItemModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("ColumnId");

                    b.Property<string>("ItemName");

                    b.Property<Guid>("PlaceId");

                    b.Property<int>("Quantity");

                    b.Property<Guid>("RackId");

                    b.Property<Guid>("RoomId");

                    b.Property<Guid>("ShelfId");

                    b.Property<Guid>("WarehouseId");

                    b.HasKey("Id");

                    b.HasIndex("ColumnId");

                    b.HasIndex("PlaceId");

                    b.HasIndex("RackId");

                    b.HasIndex("RoomId");

                    b.HasIndex("ShelfId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Item");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a6af9684-9641-4301-b0e6-00f0731c034f"),
                            ColumnId = new Guid("98ea72f0-c968-49be-8b07-a6c853bf0f9f"),
                            ItemName = "Przedmiot",
                            PlaceId = new Guid("b7ff0113-c7e4-4fe2-adee-6a5a9e458308"),
                            Quantity = 20,
                            RackId = new Guid("30daa3f2-7c48-4ffb-8732-205e0f4b27d5"),
                            RoomId = new Guid("dd20f32a-8709-4880-99bb-c58b4c701c77"),
                            ShelfId = new Guid("d28945ac-cf12-4367-8a35-8ef57652e5aa"),
                            WarehouseId = new Guid("b553eb42-2f93-4482-9cac-0cbf4c788c17")
                        });
                });

            modelBuilder.Entity("WebApi.Models.PlaceModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<Guid>("ShelfId");

                    b.HasKey("Id");

                    b.ToTable("Place");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b7ff0113-c7e4-4fe2-adee-6a5a9e458308"),
                            Name = "srodek",
                            ShelfId = new Guid("d28945ac-cf12-4367-8a35-8ef57652e5aa")
                        });
                });

            modelBuilder.Entity("WebApi.Models.RackModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("ColumnsId");

                    b.Property<string>("Name");

                    b.Property<bool>("Side");

                    b.HasKey("Id");

                    b.ToTable("Rack");

                    b.HasData(
                        new
                        {
                            Id = new Guid("30daa3f2-7c48-4ffb-8732-205e0f4b27d5"),
                            ColumnsId = new Guid("98ea72f0-c968-49be-8b07-a6c853bf0f9f"),
                            Name = "1",
                            Side = false
                        });
                });

            modelBuilder.Entity("WebApi.Models.RoomModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<Guid>("WarehouseId");

                    b.HasKey("Id");

                    b.ToTable("Room");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dd20f32a-8709-4880-99bb-c58b4c701c77"),
                            Name = "duzy",
                            WarehouseId = new Guid("b553eb42-2f93-4482-9cac-0cbf4c788c17")
                        });
                });

            modelBuilder.Entity("WebApi.Models.ShelfModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<Guid>("RackId");

                    b.HasKey("Id");

                    b.ToTable("Shelf");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d28945ac-cf12-4367-8a35-8ef57652e5aa"),
                            Name = "2",
                            RackId = new Guid("30daa3f2-7c48-4ffb-8732-205e0f4b27d5")
                        });
                });

            modelBuilder.Entity("WebApi.Models.WarehouseModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Warehouse");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b553eb42-2f93-4482-9cac-0cbf4c788c17"),
                            Name = "Martyna"
                        });
                });

            modelBuilder.Entity("WebApi.Models.ItemModel", b =>
                {
                    b.HasOne("WebApi.Models.ColumnModel", "Column")
                        .WithMany()
                        .HasForeignKey("ColumnId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebApi.Models.PlaceModel", "Place")
                        .WithMany()
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebApi.Models.RackModel", "Rack")
                        .WithMany()
                        .HasForeignKey("RackId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebApi.Models.RoomModel", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebApi.Models.ShelfModel", "Shelf")
                        .WithMany()
                        .HasForeignKey("ShelfId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebApi.Models.WarehouseModel", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
